### ISSUE TITLE
Change Comma to Semicolon in Map Pop-Up

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1026]
For Community Partners or projects with multiple Campus Partners in the Map Pop-up, change comma break to semicolon.
![image](https://user-images.githubusercontent.com/35402227/55366333-e20ba480-54ad-11e9-88b4-354627e0521e.png)

@EdemD

**Comment by vbhat0891** [comment]
I have changed it to " | " instead of a semi-colon.
![image](https://user-images.githubusercontent.com/26983338/55454403-73117700-55a5-11e9-93af-cc2f69e7e1ce.png)

**Comment by vbhat0891** [comment]
1. The messages "right-click on the marker to see a list of projects" shows up only when the number of projects is 1 or more.
![image](https://user-images.githubusercontent.com/26983338/55453708-94bd2f00-55a2-11e9-8dfc-5158a36323bb.png)

When the number of projects is 0 for a community partner, the message does not come up:
![image](https://user-images.githubusercontent.com/26983338/55453727-ac94b300-55a2-11e9-909d-962bed81e9db.png)

2. Per Keristiena's feedback, I moved the markers further apart for the legislative district map. The spiderify does not work very well when the markers are not overlapping on each other. It starts working in parts which makes accessing markers difficult. I strongly feel it is good however it is, it is clear enough for a user to know that there are multiple markers and it spawns a nice web when you click on any marker.
![image](https://user-images.githubusercontent.com/26983338/55453828-1f059300-55a3-11e9-89d1-7b58396324b5.png)

I can move them apart to whatever extent but I am not sure what she wants in this regards.

3. The campus partners are now separated by " | " instead of a " , "
![image](https://user-images.githubusercontent.com/26983338/55454332-25950a00-55a5-11e9-9838-abbc6a1ea00f.png)

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by caadler** [comment]
@EdemD  I have done most of the testing on this ticket already.  Vivek was changing one last thing and I was going to review.

**Comment by caadler** [comment]
@EdemD QA is finished for this ticket.  Everything is good.  Test plan has been saved to drive.

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1cGA_njy4OHZOGu04hWy1rupFhPyhgTTUzm1e2xIK5og
