### ISSUE TITLE
Definition not displaying on My Projects and All Projects

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1321]

**Comment by vbhat0891** [comment]
The data definition description is not provided for this in the Prod, that's the reason they are not coming up.

**Comment by Jantz021991** [comment]
There was two different ID's that were added as part of Data definitions  -
1. Logged in Community Partner had a different Project ID allocated for data definitions.
2. Logged in Campus /Community Partner had a different Project ID allocated for data definitions

With this request, made it one so that it describes the Projects for both Campus and Community Partner.

**Comment by Jantz021991** [comment]
@EdemD , QA for this is requested

**Comment by EdemD** [comment]
@pallavi0902  as QA tester

> 
> 
> @EdemD , QA for this is requested

@Jantz021991 please add an estimate at your convenience. Added you as the dev. Thanks

**Comment by pallavi0902** [comment]
QA https://drive.google.com/drive/u/0/folders/1HphhQDVJeHHbNlNzu_A7_GC3DoOeeJUK
