### ISSUE TITLE
Focus Area Report - Search functionality not working for Administrator

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2493]
Focus area report:

Logged in as Administrator, search functionality is not working/filtering the results.
Steps:
Login as Admin
Navigate to Analytics -> Reports-> Focus Area Report
Select any filter options eg. All in ‘Academic years’
Then enter a focus area name is search option, it should filter a particular focus area, but does not. 
Contrarily, it is working fine in Public user and Campus Partner view.
Either the search functionality must be removed or it should work fine. 
[Search Functionality - Focus area report as Administrator.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11155517/Search.Functionality.-.Focus.area.report.as.Administrator.docx)

**Comment by anguyen63** [comment]
Confirmed with client.
For focus area reports admin user since the sub category is implemented with another loop search cannot be done. For future recommendation is to remove search input field.

![image](https://user-images.githubusercontent.com/117041118/235559310-16e7e51d-74ef-4915-bf5f-1fdb51bf91a8.png)
