### ISSUE TITLE
Email duplication issue when registering a campus partner user

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#486]
Users should be able to be associated with more than one partner and partners should be able to be associated with multiple users. 

Currently i'm running into problems with this in multiple ways:
1) Registering a partner with the same email address is not possible - see screenshot: 
![image](https://user-images.githubusercontent.com/44984207/50918136-0141eb00-1405-11e9-9e74-cb3e36fc627f.png)

2) From the admin console, I cannot add a users to a partner if the user is already associated with another partner.

![image](https://user-images.githubusercontent.com/44984207/50918274-64338200-1405-11e9-8851-43dbcda13b06.png)

**Comment by Keristiena** [comment]
Another example: 

![image](https://user-images.githubusercontent.com/44984207/50918976-4535ef80-1407-11e9-84e8-3e88ab2c0b08.png)

**Comment by shashankpatibandla** [comment]
@Keristiena @caadler I had a question about the _*second*_ example of this ticket. When the user is already registered with his name, email and password once. He should be using the same credentials to log in to the system. If he/she wants to add a new campus partner, we will add an "add, edit or delete" options in the "organization" tab(shown in below screenshot) where the user can look up all the organisations he is related to(right now it only allows the user to be associated with one campus partner, but will be changed to show more than one). Let me know what do you think of this. 
![image](https://user-images.githubusercontent.com/35643257/52072595-e6b5ea00-254a-11e9-9282-dd4c8cc9e0a4.png)

This would give the option for the user to be associated with multiple Campus Partners and can edit or delete the campus partner when he/she is not associated anymore with one of them and ideally this would be a new feature.

C'ced @jerrodanzalone @Ruthie2018

**Comment by Keristiena** [comment]
@shashankpatibandla @cadler 
That sounds like a great way of adding yourself (as the user) to additional partners. However, part of the issue with the second screenshot is also the fact that a new partner cannot be registered, without associating that partner with a user w/email address unknown to the system. So how do I create a new community/campus partner with a user already known to the system?

**Comment by shashankpatibandla** [comment]
@Keristiena @caadler I believe we use the form in the first screenshot(in this ticket) to create a new campus partner (and we have almost fixed the first screenshot to register many campus partners with the same email address or user information). Does this explain your concern? and just as an FYI, the form from the first screenshot is under "register" tab of the homepage and the form in the second screenshot is when you click on "Campus Partner User Signup" link under the login page. Let me know if you think otherwise

As far as the user being able to log in and add, edit or delete organizations. We will create a new ticket and work on it (if the team thinks this can be done by sprint 1, we should have it. But, if not we sure will let you know). 

C'ced: @jerrodanzalone . @Ruthie2018

**Comment by caadler** [comment]
@Keristiena  @robynlloos  Per our discussion, please review for examples.

**Comment by shashankpatibandla** [comment]
@kalpanajha @EdemD QA team please test the 1st screenshot of this ticket. The 2nd screenshot is not an issue and we solved using another ticket. This ticket would only be the 1st screenshot.

C'c ed - @jerrodanzalone
