### ISSUE TITLE
View Website - Map

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#511]
Every community partner has a 'view website' hyperlink associated with their hover over detail. 'View Website' should only be viewed if there is a website on file. If there is no website associated with the community partner, we should not prompt users to click on 'view website'. 

Website entry should be optional.

**Comment by Keristiena** [comment]
![image](https://user-images.githubusercontent.com/44984207/50929117-111bf800-1422-11e9-880d-232bc880fe80.png)

**Comment by vbhat0891** [comment]
`Instead of View website, I have displayed the website itself and nothing is displayed if there isn't a website provided.
![image](https://user-images.githubusercontent.com/26983338/54882417-d4a84780-4e27-11e9-971c-322811747f5d.png)

When no website is provided, it will be blank. Below is an example of the same- 
![image](https://user-images.githubusercontent.com/26983338/54882432-f7d2f700-4e27-11e9-9a9a-6a1d255222f7.png)

**Comment by duwaezuoke** [comment]
QA tested and confirmed done-done. Reference: https://drive.google.com/open?id=1RpXkOVTo6tgTxTUbUbBV9jFY28_tqYGp8fNeNGBAjI4
