### ISSUE TITLE
General Label Feedback to Analytics 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#528]
All Reports:
o	Edit “Mission Area” to “Mission Areas”
o	Edit “Engagement Type” to “Engagement Types”
o	Edit “Project Reports” to “Projects”

Make the in-report titles consistent with the drop down edits above
 
Grays appear to be inconsistent 

-	Edit “Engagement Type” to read “Engagement Types”
-	Edit “Community Type” to read “Community Partner Type”
-	Edit “Academic Year” to read “Academic Years”
-	Edit “Campus Partner” to read “Campus Partners”
-	Edit “CEC Partner” to read “CEC Building Partners”

Ensure consistency in the following labels: 
o	Number of UNO Students
o	Number of UNO Students Hours

Be consistent with the headings of the filters (for instance plural versus singular) – it makes sense that the main headings of these be plural since there are multiple in the drop downs

Report: Mission Area
-	Edit “Report: Mission Area” to “Report: Mission Areas”

Report: Engagement Type
-	Edit report name in gray bar to be consistent with drop-down

**Comment by jnabity** [comment]
@Ruthie2018 There is a discrepancy on the Analytics > Reports menu. When you are not logged in or when you are logged in as a campus user the menu shows 'Projects'. However, as an Admin is shows 'Project Report'.

**Comment by jnabity** [comment]
@Ruthie2018 found a few things to look at for this ticket.
The "Community Types" dropdown did not get renamed as expected. Expected filter to be named "Community Partner Types".
<img width="1677" alt="Screen Shot 2019-03-11 at 1 43 59 PM" src="https://user-images.githubusercontent.com/29965889/54157610-aafa2400-4416-11e9-8a48-c122541638cd.png">
On the Projects Reports, the Engagement Type filter is showing singular instead of plural.
<img width="1681" alt="Screen Shot 2019-03-11 at 2 23 40 PM" src="https://user-images.githubusercontent.com/29965889/54162273-e995db80-4422-11e9-8c05-86fd7feed8cc.png">

**Comment by Ruthie2018** [comment]
those 2 labels are fixed.

**Comment by jnabity** [comment]
Testing passed. Test script link below:
https://docs.google.com/spreadsheets/d/14S3Gn5k397O8xS6fIVu5p_hdtrOs-KDgB6IMkPeT5mw/edit#gid=1823693423
