### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#55]
Based on feedback from Sprint 1 demo, updates need to be made. This includes fixing naming of forms, such as spacing and capitalization. The header needs to be smaller.

**Comment by indraTeja** [comment]
@Goutham2591 @TarekRamesses @Arti012 
I think we need to discuss this tonight in class. We need to find a way to deploy images, they are getting broken. I looked up online and found out, we need to store the image in an external source such as AWS. Heroku doesn't store image longer than 24 hours, since its a free or any other reason. Thanks.
![capture](https://user-images.githubusercontent.com/13390222/49246623-0447c580-f3db-11e8-80ba-15cbe8e4b871.PNG)
